package com.epam.sb.students.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Course service. Represents a row in the &quot;student_Course&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.epam.sb.students.model.impl.CourseModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.epam.sb.students.model.impl.CourseImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Course
 * @see com.epam.sb.students.model.impl.CourseImpl
 * @see com.epam.sb.students.model.impl.CourseModelImpl
 * @generated
 */
public interface CourseModel extends BaseModel<Course> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a course model instance should use the {@link Course} interface instead.
     */

    /**
     * Returns the primary key of this course.
     *
     * @return the primary key of this course
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this course.
     *
     * @param primaryKey the primary key of this course
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the course ID of this course.
     *
     * @return the course ID of this course
     */
    public long getCourseId();

    /**
     * Sets the course ID of this course.
     *
     * @param courseId the course ID of this course
     */
    public void setCourseId(long courseId);

    /**
     * Returns the course name of this course.
     *
     * @return the course name of this course
     */
    @AutoEscape
    public String getCourseName();

    /**
     * Sets the course name of this course.
     *
     * @param courseName the course name of this course
     */
    public void setCourseName(String courseName);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.epam.sb.students.model.Course course);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.epam.sb.students.model.Course> toCacheModel();

    @Override
    public com.epam.sb.students.model.Course toEscapedModel();

    @Override
    public com.epam.sb.students.model.Course toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
